
name: device_safety_info_example
description: Demonstrates how to use the device_safety_info plugin.
publish_to: 'none'

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  device_safety_info:
    path: ../
  cupertino_icons: ^1.0.8

  material_ui: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  patrol: ^4.6.1

  test_api: any
flutter:
  uses-material-design: true
