
name: devicesafetyinfo_example
description: Demonstrates how to use the devicesafetyinfo plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  devicesafetyinfo:

    path: ../


  cupertino_icons:

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true

